// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dugout.WebApi.Models;

namespace dugout.WebApi.Migrations
{
    [DbContext(typeof(MlbContext))]
    [Migration("20190416130437_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("dugout.WebApi.Models.Division", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("link");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Division");
                });

            modelBuilder.Entity("dugout.WebApi.Models.League", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("link");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("League");
                });

            modelBuilder.Entity("dugout.WebApi.Models.Sport", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("link");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Sport");
                });

            modelBuilder.Entity("dugout.WebApi.Models.SpringLeague", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("abbreviation");

                    b.Property<string>("link");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("SpringLeague");
                });

            modelBuilder.Entity("dugout.WebApi.Models.Team", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("abbreviation");

                    b.Property<bool>("active");

                    b.Property<string>("allStarStatus");

                    b.Property<int?>("divisionid");

                    b.Property<string>("fileCode");

                    b.Property<string>("firstYearOfPlay");

                    b.Property<int?>("leagueid");

                    b.Property<string>("link");

                    b.Property<string>("locationName");

                    b.Property<string>("name");

                    b.Property<string>("shortName");

                    b.Property<int?>("sportid");

                    b.Property<int?>("springLeagueid");

                    b.Property<string>("teamCode");

                    b.Property<string>("teamName");

                    b.Property<int?>("venueid");

                    b.HasKey("id");

                    b.HasIndex("divisionid");

                    b.HasIndex("leagueid");

                    b.HasIndex("sportid");

                    b.HasIndex("springLeagueid");

                    b.HasIndex("venueid");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("dugout.WebApi.Models.Venue", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("link");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Venue");
                });

            modelBuilder.Entity("dugout.WebApi.Models.Team", b =>
                {
                    b.HasOne("dugout.WebApi.Models.Division", "division")
                        .WithMany()
                        .HasForeignKey("divisionid");

                    b.HasOne("dugout.WebApi.Models.League", "league")
                        .WithMany()
                        .HasForeignKey("leagueid");

                    b.HasOne("dugout.WebApi.Models.Sport", "sport")
                        .WithMany()
                        .HasForeignKey("sportid");

                    b.HasOne("dugout.WebApi.Models.SpringLeague", "springLeague")
                        .WithMany()
                        .HasForeignKey("springLeagueid");

                    b.HasOne("dugout.WebApi.Models.Venue", "venue")
                        .WithMany()
                        .HasForeignKey("venueid");
                });
#pragma warning restore 612, 618
        }
    }
}
